# Demo Exception 

* Found more [exception](https://programming.guide/java/list-of-java-exceptions.html) 

## Try Catch

```
public class WildException4 {

    public static void main(String[] args) {
        try {
            int i = 3;
            int j = 0;
            System.out.println("result = " + (i / j));
        } catch (ArithmeticException e) {
            throw new ArithmeticException("Can not devide by 0");
        } finally {
            System.out.println("action always done");
        }
    }
}
```

## 